apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-wbho
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-wbho
    app.kubernetes.io/part-of: java-springboot-hello
  name: java-springboot-hello-wbho
  namespace: eric-deandrea-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: java-springboot-hello-wbho
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: java-springboot-hello-wbho
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:eric-deandrea-tenant-java-springboot-hello-wbho
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
status: {}
