apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-wbho
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-wbho
    app.kubernetes.io/part-of: java-springboot-hello
  name: java-springboot-hello-wbho
  namespace: eric-deandrea-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-springboot-hello-wbho
    weight: 100
status: {}
