apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-wbho
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-wbho
    app.kubernetes.io/part-of: java-springboot-hello
  name: java-springboot-hello-wbho
  namespace: eric-deandrea-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: java-springboot-hello-wbho
status:
  loadBalancer: {}
